version: '3.8'
services:
  app:
    build: .
    container_name: php_slim_smarty
    ports:
      - "8180:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
